---
- hosts: all
  become: true
  pre_tasks:
    - name: update apt cache
      apt:
        update_cache: yes
        cache_valid_time: 7200
      changed_when: false

    - name: set timezone
      community.general.timezone:
        name: Europe/Kyiv

- hosts: server
  become: true
  tasks:
    - name: install dependencies
      apt:
        name: 
        - curl
        - openssh-server
        - ca-certificates
        - tzdata
        - perl
        state: present

    - name: Check if gitlab repo is installed
      stat: 
        path: /etc/apt/sources.list.d/gitlab_gitlab-ce.list
      register: gitlab_repo_installed

    - name: download gitlab package repo script
      get_url: 
        url: https://packages.gitlab.com/install/repositories/gitlab/gitlab-ce/script.deb.sh
        dest: /tmp/script.deb.sh
        mode: 0755
      when: gitlab_repo_installed.stat.exists == false

    - name: install gitlab package repo
      command: /tmp/script.deb.sh
      when: gitlab_repo_installed.stat.exists == false

    - name: install gitlab
      environment:
        EXTERNAL_URL: "{{ CI_SERVER_URL }}"
      apt:
        name: gitlab-ce=16.11.6-ce.0
        state: present

    - name: Upload gitlab.rb 
      copy:
        src: files/gitlab.rb
        dest: /etc/gitlab/gitlab.rb
        force: yes
      notify: gitlab_ctl_reconfigure

  handlers:
    - name: gitlab_ctl_reconfigure
      shell: gitlab-ctl reconfigure

- hosts: runner
  become: true
  vars:
    android_sdk_root: "/usr/local/android/sdk"
    sdkmanager_bin: "{{ android_sdk_root }}/cmdline-tools/latest/bin/sdkmanager"
  tasks:

    - name: Install dependencies
      tags: android
      apt:
        name: 
          - unzip
          - openjdk-17-jdk-headless


    - name: Change hosts file (only for testing purpose, otherwise DNS is used)
      tags: local
      lineinfile:
        path: /etc/hosts
        regexp: "^{{ CI_SERVER_URL }}"
        line: "{{ CI_SERVER_URL}} 192.168.56.10" 

    - name: Set global environment variables
      lineinfile:
        path: /etc/environment
        regexp: "^CI_SERVER_URL="
        line: "CI_SERVER_URL={{ CI_SERVER_URL }}"
        create: yes


    - name: Check if gitlab runner package is added
      stat:
        path: /etc/apt/sources.list.d/runner_gitlab-runner.list
      register: runner_repo_installed

    - name: download gitlab runner package repo script
      get_url:
        url: https://packages.gitlab.com/install/repositories/runner/gitlab-runner/script.deb.sh
        dest: /tmp/script.deb.sh
        mode: 0755
      when: runner_repo_installed.stat.exists == false

    - name: install gitlab runner package repo
      shell: /tmp/script.deb.sh
      when: runner_repo_installed.stat.exists == false

    - name: install gitlab runner
      apt:
        name: gitlab-runner=16.11.2-1
        state: present

    - name: Set Android SDK Root env var
      lineinfile:
        path: /etc/environment
        regex: "^ANDROID_SDK_ROOT"
        line: "ANDROID_SDK_ROOT={{ android_sdk_root }}"

    - name: Create Android SDK dir structure
      file:
        path: "{{ item.path }}"
        state: "{{ item.state }}"
        mode: "{{ item.mode }}"
      with_items:
        - { path: "{{ android_sdk_root }}", state: "directory", mode: "0755" }
        - { path: "{{ android_sdk_root }}/cmdline-tools", state: "directory", mode: "0755" }

    - name: Download Android cmd tools
      unarchive:
        src: https://dl.google.com/android/repository/commandlinetools-linux-11076708_latest.zip
        dest: "{{ android_sdk_root }}/cmdline-tools/"
        creates: "{{ android_sdk_root }}/cmdline-tools/latest"
        remote_src: yes
      register: android_cmdtools

    - name: Rename cmdline-tools dir
      shell: mv "{{ android_sdk_root }}/cmdline-tools/cmdline-tools" "{{ android_sdk_root }}/cmdline-tools/latest"
      when: android_cmdtools.changed == true

    - name: Install android dependencies
      script: files/install_android.sh